name: provider_example_app
description: Bottom Navigaton menu with provider.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+3

flutter:
  uses-material-design: true